ilac_public:
    resource: "@IlacPublicBundle/Controller/"
    type:     annotation
    prefix:   /

ilac_main:
    resource: "@IlacMainBundle/Resources/config/routing.yml"
    prefix:   /my/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
