ilac_main_homepage:
    path:     /
    defaults: { _controller: IlacMainBundle:Default:index }
ilac_main_new:
    path:     /new
    defaults: { _controller: IlacMainBundle:Default:new }
ilac_main_new_bolus:
    path:     /bolus
    defaults: { _controller: IlacMainBundle:Default:newBolus }
ilac_main_calc_bolus:
    path:     /bolus/calc/{testID}/{carb}
    defaults: { _controller: IlacMainBundle:Default:calcBolus }
    options:
        expose: true
